### PR TITLE
Us 34 -- User Story Complete -- Merge back to Master branch

### PR DESCRIPTION
**Pull request by ghgofort**
I will merge this in a day or two once everyone has a chance to review any code that they have time to review.
-Galen

### CODE REVIEW

**Comment by tjjohn1** [comment]
All JUnit Tests passed except for "testGetTemplateFromName"

[CodeRev_Defect_List_US-34.pdf](https://github.com/cst316/spring16project-Team-Flagstaff/files/147764/CodeRev_Defect_List_US-34.pdf)

**Comment by ghgofort** [comment]
Can you tell me what is not passing on this?
[image: Inline image 1]

It all runs fine on my machine.

Galen

**Comment by ghgofort** [comment]
I have fixed the issues and made another commit.  It wasn't properly creating the default template.  That is fixed.  I also changed the test to create its own template and then check for that one to be less ambiguous about what functionality was being tested.

[bug_fix_log_US_34.pdf](https://github.com/cst316/spring16project-Team-Flagstaff/files/147842/bug_fix_log_US_34.pdf)

**Comment by ghgofort** [comment]
Not changing Tests that are failing the Travis-ci because these are being worked on in a separate branch and this would cause conflicts.

**Comment by ghgofort** [comment]
Resolved conflicts - Completing the request

**Pull request merged**
